/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.remote.server;



import connection.connectionServer;
import java.awt.Color;
import java.net.MalformedURLException;
import java.rmi.Naming;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.util.Iterator;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JTextField;
import org.hibernate.Session;
import org.hibernate.Transaction;
import pojo.Chatgroups;



public class StartServer extends javax.swing.JFrame {

    /**
     * Creates new form Run
     */
    int hostNo=0;
    public StartServer() {
        initComponents();
        getRootPane().setBorder(BorderFactory.createMatteBorder(1, 1, 2, 2, Color.red));
        this.setLocationRelativeTo(null);
        jPanel3.setVisible(true);
        jPanel2.setVisible(false);
        panelServer.setVisible(false);
        String chatHost=null;
        
        
        Session s = connectionServer.getSessionFactory().openSession();
        Transaction t = s.beginTransaction();
        List cgs = s.createQuery("from Chatgroups").list();
        
        //listAll
        for (Iterator iterator = cgs.iterator(); iterator.hasNext();) {
            //Users next = (Users) iterator.next();
            Chatgroups next = (Chatgroups) iterator.next();
            //System.out.println(next.getGroupName());
            //System.out.println(next.getHostId());
           
            
            jComboBox1.addItem(next.getGroupName());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelServer = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        kButton4 = new com.k33ptoo.components.KButton();
        jLabel14 = new javax.swing.JLabel();
        kButton5 = new com.k33ptoo.components.KButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        host = new javax.swing.JTextField();
        chatname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        kButton2 = new com.k33ptoo.components.KButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        kButton1 = new com.k33ptoo.components.KButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelServer.setBackground(new java.awt.Color(0, 0, 0));
        panelServer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        jLabel11.setText("Running");
        panelServer.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, -1, 30));

        panelServer.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 240, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 0));
        jLabel12.setText("HOST");
        panelServer.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 360, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 0));
        jLabel13.setText("OTHER HOSTS");
        panelServer.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, -1, -1));

        kButton4.setText("DELETE");
        kButton4.setkBackGroundColor(new java.awt.Color(153, 0, 0));
        kButton4.setkBorderRadius(20);
        kButton4.setkEndColor(new java.awt.Color(102, 0, 0));
        kButton4.setkHoverEndColor(new java.awt.Color(153, 0, 102));
        kButton4.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton4.setkHoverStartColor(new java.awt.Color(153, 0, 0));
        kButton4.setkStartColor(new java.awt.Color(204, 0, 0));
        kButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton4ActionPerformed(evt);
            }
        });
        panelServer.add(kButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 140, 30));

        jLabel14.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 0));
        jLabel14.setText("HOST");
        panelServer.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 330, -1, -1));

        kButton5.setText("END");
        kButton5.setkBackGroundColor(new java.awt.Color(153, 0, 0));
        kButton5.setkBorderRadius(20);
        kButton5.setkEndColor(new java.awt.Color(102, 0, 0));
        kButton5.setkHoverEndColor(new java.awt.Color(153, 0, 102));
        kButton5.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton5.setkHoverStartColor(new java.awt.Color(153, 0, 0));
        kButton5.setkStartColor(new java.awt.Color(204, 0, 0));
        kButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton5ActionPerformed(evt);
            }
        });
        panelServer.add(kButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, 160, 30));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imges/icons8_Logout_20px_2.png"))); // NOI18N
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        panelServer.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 30, 30));

        jLabel16.setForeground(new java.awt.Color(255, 0, 0));
        panelServer.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 190, 20));

        jLabel17.setForeground(new java.awt.Color(255, 204, 0));
        panelServer.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 384, 200, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imges/fdfd.jpg"))); // NOI18N
        panelServer.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 440));

        jPanel1.add(panelServer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 430));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(new java.awt.Color(0, 153, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("WELCOME TO SERVER");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));

        host.setBackground(new java.awt.Color(51, 51, 51));
        host.setFont(new java.awt.Font("Segoe UI Historic", 0, 12)); // NOI18N
        host.setForeground(new java.awt.Color(255, 255, 255));
        host.setText("1234");
        host.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 0, 0)));
        host.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                hostFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                hostFocusLost(evt);
            }
        });
        jPanel3.add(host, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 282, 35));

        chatname.setBackground(new java.awt.Color(51, 51, 51));
        chatname.setFont(new java.awt.Font("Segoe UI Historic", 0, 12)); // NOI18N
        chatname.setForeground(new java.awt.Color(255, 255, 255));
        chatname.setText("chat");
        chatname.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 0, 0)));
        chatname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                chatnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                chatnameFocusLost(evt);
            }
        });
        jPanel3.add(chatname, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 282, 35));

        jLabel6.setFont(new java.awt.Font("Segoe UI Historic", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("HOST ID");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Historic", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("CHAT NAME");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));

        kButton2.setText("START CHAT");
        kButton2.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        kButton2.setkBorderRadius(30);
        kButton2.setkEndColor(new java.awt.Color(102, 204, 0));
        kButton2.setkHoverEndColor(new java.awt.Color(0, 153, 0));
        kButton2.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton2.setkHoverStartColor(new java.awt.Color(0, 153, 153));
        kButton2.setkStartColor(new java.awt.Color(0, 153, 102));
        kButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(kButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, -1, 36));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imges/icons8_Logout_20px_2.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 15, -1, 33));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imges/fdfd.jpg"))); // NOI18N
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 430));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 430));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField2.setBackground(new java.awt.Color(0, 0, 0));
        jTextField2.setForeground(new java.awt.Color(255, 0, 0));
        jTextField2.setText("User Name");
        jTextField2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 0, 0)));
        jPanel2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 190, 30));

        jPasswordField1.setBackground(new java.awt.Color(0, 0, 0));
        jPasswordField1.setForeground(new java.awt.Color(255, 0, 0));
        jPasswordField1.setText("password");
        jPasswordField1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 0, 0)));
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        jPanel2.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 190, 30));

        kButton1.setText("LOGIN");
        kButton1.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        kButton1.setkBorderRadius(30);
        kButton1.setkEndColor(new java.awt.Color(255, 0, 0));
        kButton1.setkHoverEndColor(new java.awt.Color(102, 0, 0));
        kButton1.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        kButton1.setkHoverStartColor(new java.awt.Color(204, 0, 0));
        kButton1.setkStartColor(new java.awt.Color(102, 0, 0));
        kButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(kButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 160, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("LOGIN");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 60, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 0));
        jLabel3.setText("Password");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 100, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 0, 0));
        jLabel4.setText("User Name");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 100, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imges/820.gif"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 490, 350));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 430));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void kButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton1ActionPerformed
        System.out.println(""+jTextField2.getText());
        
            jPanel3.setVisible(true);
        
    }//GEN-LAST:event_kButton1ActionPerformed

    private void kButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton2ActionPerformed
        
        int Serverhost= Integer.parseInt(host.getText());
        String chatName=chatname.getText();
        hostNo=Serverhost;
        //runnin
        jLabel14.setText(host.getText());
        jLabel12.setText(chatName);
        System.out.println("host: "+Serverhost);
        System.out.println("ch" + chatName);
        try {
            LocateRegistry.createRegistry(Serverhost);
            //start server
            Naming.rebind("rmi://localhost:"+Serverhost+"/"+chatName+"",new ChatServer());
            
            Session s = connectionServer.getSessionFactory().openSession();
            Transaction t=s.beginTransaction();
            Chatgroups cg = new Chatgroups();
            cg.setGroupName(chatName);
            cg.setHostId(Serverhost);
            cg.setStatus(1);
            
            s.save(cg);
            t.commit();
            System.out.println("Group added to DB");
            s.close();

           
            
            System.out.println("Server Started ...");
            jPanel3.setVisible(false);
            panelServer.setVisible(true);
        } catch (MalformedURLException | RemoteException ex) {
            System.out.println("Error: " + ex.getMessage());
        }
        
        
        
    }//GEN-LAST:event_kButton2ActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        System.exit(0);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void kButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton4ActionPerformed
        //deleteOt
        String chatName=jComboBox1.getSelectedItem().toString();
        Session s = connectionServer.getSessionFactory().openSession();
        Transaction t = s.beginTransaction();
        List cgs = s.createQuery("from Chatgroups").list();
        int id=0;
        
        for (Iterator iterator = cgs.iterator(); iterator.hasNext();) {
            //Users next = (Users) iterator.next();
            Chatgroups next = (Chatgroups) iterator.next();
            
            String cc=next.getGroupName();
            if(cc.equals(chatName)){
                id=next.getChatId();
            }
            //System.out.println(next.getHostId());
        }
        
        Chatgroups chG = (Chatgroups) s.get(Chatgroups.class, id);
        s.delete(chG);
        jLabel16.setText(chatName+" Deleted Successfuly");
    }//GEN-LAST:event_kButton4ActionPerformed

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel15MouseClicked

    private void kButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton5ActionPerformed
        int id=hostNo;
        Session s = connectionServer.getSessionFactory().openSession();
        Transaction t = s.beginTransaction();
        Chatgroups chG = (Chatgroups) s.get(Chatgroups.class, id);
        s.delete(chG);
        jLabel17.setText("Host Stopped");
        
    }//GEN-LAST:event_kButton5ActionPerformed

    private void hostFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_hostFocusGained
        String userPW=String.valueOf(host.getText()).trim().toLowerCase();
        if(userPW.equals("1234") || userPW.equals("")){
            host.setText("");
            
        }
    }//GEN-LAST:event_hostFocusGained

    private void hostFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_hostFocusLost
        String userNameVal=host.getText().trim().toLowerCase();
        if(userNameVal.equals("1234") || userNameVal.equals("")){
            host.setText("1234");
            host.setForeground(new Color(255,255,255));
        }
    }//GEN-LAST:event_hostFocusLost

    private void chatnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_chatnameFocusGained
        String userPW=String.valueOf(chatname.getText()).trim().toLowerCase();
        if(userPW.equals("chat") || userPW.equals("")){
            chatname.setText("");
            
        }
    }//GEN-LAST:event_chatnameFocusGained

    private void chatnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_chatnameFocusLost
        String userNameVal=chatname.getText().trim().toLowerCase();
        if(userNameVal.equals("chat") || userNameVal.equals("")){
            chatname.setText("chat");
            chatname.setForeground(new Color(255,255,255));
        }
    }//GEN-LAST:event_chatnameFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartServer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField chatname;
    private javax.swing.JTextField host;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField2;
    private com.k33ptoo.components.KButton kButton1;
    private com.k33ptoo.components.KButton kButton2;
    private com.k33ptoo.components.KButton kButton4;
    private com.k33ptoo.components.KButton kButton5;
    private javax.swing.JPanel panelServer;
    // End of variables declaration//GEN-END:variables
}
